"""
File: backend/tools/check_labels.py

Summary:
データ抽出スキーマと日本語表示ラベルの網羅性を検証するチェックツール。
Pydanticモデル（`PatientExtractionSchema`）から生成されるすべてのデータキーを抽出し、それが `constants.py` の `PATIENT_FIELD_LABELS` に日本語ラベルとして定義されているかを照合します。スキーマ変更時にラベル定義の追加忘れを検知（Missing検知）し、不要になった古いキー（Unused検知）を警告します。

Tags: Tool, Utility, Validation, Schema, Labels, Coverage
"""

import sys
import os
from pathlib import Path

# パス設定: backendディレクトリをパスに追加して app モジュールをインポート可能にする
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

try:
    from app.schemas.extraction_schemas import (
        PatientExtractionSchema,
        BasicInfoSchema,
        MedicalRiskSchema,
        FunctionalStatusSchema,
        BasicMovementSchema,
        AdlSchema,
        NutritionSchema,
        SocialSchema,
        GoalSettingSchema,
        SignatureSchema
    )
    from app.core.constants import PATIENT_FIELD_LABELS
except ImportError as e:
    print(f"Import Error: {e}")
    print("Run this script from the 'backend' directory or ensure python path is set.")
    sys.exit(1)

def main():
    print("🔍 Checking label definition coverage...")

    # 1. ダミーデータでスキーマを初期化
    # 必須フィールドがないため、引数なしで初期化可能です（Pydanticのdefault/Optional設定に依存）
    try:
        dummy_schema = PatientExtractionSchema(
            basic=BasicInfoSchema(),
            medical=MedicalRiskSchema(),
            function=FunctionalStatusSchema(),
            basic_movement=BasicMovementSchema(),
            adl=AdlSchema(),
            nutrition=NutritionSchema(),
            social=SocialSchema(),
            goals=GoalSettingSchema(),
            signature=SignatureSchema()
        )
    except Exception as e:
        print(f"❌ Failed to instantiate schema: {e}")
        sys.exit(1)

    # 2. フラット形式に変換して、全キーを取得
    flat_data = dummy_schema.export_to_mapping_format()
    system_keys = set(flat_data.keys())

    # 3. constants.py で定義済みのキーを取得
    defined_keys = set(PATIENT_FIELD_LABELS.keys())

    # 4. 比較: スキーマにあるが、ラベル定義がないキー (Missing)
    missing_labels = system_keys - defined_keys
    
    # 5. 比較: ラベル定義はあるが、スキーマにないキー (Unused/Legacy)
    unused_labels = defined_keys - system_keys

    # --- 結果出力 ---
    print(f"   Keys in Schema:    {len(system_keys)}")
    print(f"   Keys in Constants: {len(defined_keys)}")

    if missing_labels:
        print("\n❌ [FAIL] Missing Label Definitions Detected!")
        print("The following keys exist in the system (extraction_schemas.py)")
        print("but are NOT defined in 'constants.py' (PATIENT_FIELD_LABELS):")
        print("-" * 60)
        for k in sorted(missing_labels):
            print(f" - {k}")
        print("-" * 60)
        print("👉 Action: Add Japanese labels for these keys in 'backend/app/core/constants.py'.")
        sys.exit(1)
    else:
        print("\n✅ [PASS] All schema keys have corresponding label definitions.")

    if unused_labels:
        print(f"\n⚠️  [WARN] Unused Labels Detected ({len(unused_labels)} keys):")
        print("   (These keys exist in constants.py but are not generated by the current schema logic.)")
        # 詳細が見たい場合はコメントアウトを外す
        # for k in sorted(unused_labels):
        #     print(f"   - {k}")

if __name__ == "__main__":
    main()