"""Add analysis columns to patients_view

Revision ID: 39024f96600b
Revises: 3b7d24c1aae5
Create Date: 2026-02-07 22:04:54.506482+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector

# revision identifiers, used by Alembic.
revision: str = '39024f96600b'
down_revision: Union[str, Sequence[str], None] = '3b7d24c1aae5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients_view', sa.Column('onset_date', sa.Date(), nullable=True, comment='発症日'))
    op.add_column('patients_view', sa.Column('outcome', sa.String(length=50), nullable=True, comment='転帰（自宅復帰/転院など）'))
    op.add_column('patients_view', sa.Column('total_fim_admission', sa.Integer(), nullable=True, comment='入院時FIM合計'))
    op.add_column('patients_view', sa.Column('total_fim_discharge', sa.Integer(), nullable=True, comment='退院時FIM合計'))
    op.add_column('patients_view', sa.Column('mental_min', sa.Float(), nullable=True, comment='ONNX: メンタル最大リスク(Min)'))
    op.add_column('patients_view', sa.Column('mental_mean', sa.Float(), nullable=True, comment='ONNX: 平均意欲スコア(Mean)'))
    op.add_column('patients_view', sa.Column('mental_std', sa.Float(), nullable=True, comment='ONNX: 情緒のブレ(Std)'))
    op.add_column('patients_view', sa.Column('physical_mean', sa.Float(), nullable=True, comment='ONNX: 身体状態スコア(Mean)'))
    op.add_column('patients_view', sa.Column('social_vector', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True))
    op.add_column('patients_view', sa.Column('plan_text', sa.Text(), nullable=True, comment='過去の計画書正解データ'))
    op.create_index('ix_patients_social_vector', 'patients_view', ['social_vector'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'social_vector': 'vector_l2_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_patients_social_vector', table_name='patients_view', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'social_vector': 'vector_l2_ops'})
    op.drop_column('patients_view', 'plan_text')
    op.drop_column('patients_view', 'social_vector')
    op.drop_column('patients_view', 'physical_mean')
    op.drop_column('patients_view', 'mental_std')
    op.drop_column('patients_view', 'mental_mean')
    op.drop_column('patients_view', 'mental_min')
    op.drop_column('patients_view', 'total_fim_discharge')
    op.drop_column('patients_view', 'total_fim_admission')
    op.drop_column('patients_view', 'outcome')
    op.drop_column('patients_view', 'onset_date')
    # ### end Alembic commands ###
