"""Initial migration

Revision ID: 3b7d24c1aae5
Revises: 
Create Date: 2026-01-30 18:35:41.672299+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b7d24c1aae5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients_view',
    sa.Column('hash_id', sa.String(length=64), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('diagnosis_code', sa.String(length=50), nullable=True, comment='ICD-10等の疾患コード'),
    sa.Column('admission_date', sa.Date(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=False, comment='中間DBへの同期日時'),
    sa.PrimaryKeyConstraint('hash_id')
    )
    op.create_index(op.f('ix_patients_view_hash_id'), 'patients_view', ['hash_id'], unique=False)
    op.create_table('documents_view',
    sa.Column('doc_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hash_id', sa.String(length=64), nullable=False),
    sa.Column('doc_date', sa.Date(), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=False, comment='リハビリ実施録, 退院サマリ, etc.'),
    sa.Column('source_type', sa.String(length=20), nullable=False, comment='EHR, UPLOAD(外部資料)'),
    sa.Column('summary_text', sa.Text(), nullable=True, comment='LLMコンテキスト用の要約'),
    sa.Column('original_text', sa.Text(), nullable=True, comment='参照用の原文（匿名化済み）'),
    sa.Column('entities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('content_vector', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.ForeignKeyConstraint(['hash_id'], ['patients_view.hash_id'], ),
    sa.PrimaryKeyConstraint('doc_id')
    )
    op.create_index('ix_documents_entities', 'documents_view', ['entities'], unique=False, postgresql_using='gin')
    op.create_index('ix_documents_vector', 'documents_view', ['content_vector'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'content_vector': 'vector_l2_ops'})
    op.create_index(op.f('ix_documents_view_hash_id'), 'documents_view', ['hash_id'], unique=False)
    op.create_table('plan_data_store',
    sa.Column('plan_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hash_id', sa.String(length=64), nullable=False),
    sa.Column('doc_date', sa.Date(), nullable=False),
    sa.Column('format_version', sa.String(length=20), nullable=False, comment='様式のバージョン管理'),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hash_id'], ['patients_view.hash_id'], ),
    sa.PrimaryKeyConstraint('plan_id')
    )
    op.create_index(op.f('ix_plan_data_store_hash_id'), 'plan_data_store', ['hash_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plan_data_store_hash_id'), table_name='plan_data_store')
    op.drop_table('plan_data_store')
    op.drop_index(op.f('ix_documents_view_hash_id'), table_name='documents_view')
    op.drop_index('ix_documents_vector', table_name='documents_view', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'content_vector': 'vector_l2_ops'})
    op.drop_index('ix_documents_entities', table_name='documents_view', postgresql_using='gin')
    op.drop_table('documents_view')
    op.drop_index(op.f('ix_patients_view_hash_id'), table_name='patients_view')
    op.drop_table('patients_view')
    # ### end Alembic commands ###
